version: "3.9"
services:
  recipe-pg:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: recipe_db
    ports:
      - "5433:5432"
